export const ORDER_BOOK_DISPLAY_BOTH = 0;
export const ORDER_BOOK_DISPLAY_BUY_ONLY = 1;
export const ORDER_BOOK_DISPLAY_SELL_ONLY = 2;

export const ORDER_BOOK_DISPLAY_BOTH_LENGTH = 12;
export const ORDER_BOOK_DISPLAY_BUY_SELL_ONLY_LENGTH = 26;
export default {
  ORDER_BOOK_DISPLAY_BOTH,
  ORDER_BOOK_DISPLAY_BUY_ONLY,
  ORDER_BOOK_DISPLAY_SELL_ONLY,
  ORDER_BOOK_DISPLAY_BOTH_LENGTH,
  ORDER_BOOK_DISPLAY_BUY_SELL_ONLY_LENGTH,
};
export enum STELLAR_ASSET_TYPE {
  NATIVE = 1,
  CREDIT_ALPHANUM4 = 2,
  CREDIT_ALPHANUM12 = 3,
}
